#test error reporting for different types of bad input

use t::TestMRCConverter;
use Test::More;
plan tests => 2 * blocks();
use Test::XML;
use Test::LongString;

#loop through all blocks, convert the input, and compare with the output
for my $block ( blocks('input') ){
	my ($tbx, $log) = @{ $block->input };
	
	#compare tbx; check for undefs first
	if(defined $tbx and defined $block->tbx){
		is_xml($tbx, $block->tbx, "'" . $block->name . "' correct TBX output");
	}
	else{
		is($tbx,$block->tbx, "'" . $block->name . "' correct TBX output");
	}
	
	#check log for correct messages
	is_string($log, $block->log,  "'" . $block->name . "' correct error(s) logged")
		or print $log;
}

__DATA__
=== LangSet level out of order

--- input convert
=MRCtermTable
A	workingLanguage	en
A	sourceDesc	a book about animals
C003	subjectField	animal book
C003en1	term	chicken
C003en1	partOfSpeech	noun
C003en	note	my English is pretty good, isn't it?

--- log fix_version
[MSG] MRC2TBX converter version [version]
[ERROR] LangSet-level row out of order in line 7, skipped.
[MSG] File includes IDs:
	C003
	C003en1

--- tbx fix_version
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version [version]</p>
			</sourceDesc>
			<sourceDesc>
				<p>a book about animals</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">animal book</descrip>
				</descripGrp>
				<langSet xml:lang="en">
					<tig id="C003en1">
						<term>chicken</term>
						<termNote type="partOfSpeech">noun</termNote>
					</tig>
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>

=== Concept level out of order

--- input convert
=MRCtermTable
A	workingLanguage	en
A	sourceDesc	a book about animals
C003	subjectField	animal book
C003en1	term	chicken
C003en1	partOfSpeech	noun
C003	note	that's a real story

--- log fix_version
[MSG] MRC2TBX converter version [version]
[ERROR] Concept-level row out of order in line 7, skipped.
[MSG] File includes IDs:
	C003
	C003en1

--- tbx fix_version
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version [version]</p>
			</sourceDesc>
			<sourceDesc>
				<p>a book about animals</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">animal book</descrip>
				</descripGrp>
				<langSet xml:lang="en">
					<tig id="C003en1">
						<term>chicken</term>
						<termNote type="partOfSpeech">noun</termNote>
					</tig>
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>

=== Term level disallowed data category

--- input convert
=MRCtermTable
A	workingLanguage	en
A	sourceDesc	a book about animals
C003	subjectField	animal book
C003en1	xGraphic	My pet chicken is named wanda.	Link: wanda.jpg
C003en1	subjectField	Restaurant Menus
C003en1	definition	a squaky bird
C003en1	term	chicken
C003en1	partOfSpeech	noun

--- log fix_version
[MSG] MRC2TBX converter version [version]
[ERROR] Data category 'xGraphic' not allowed at the Term level in line 5, skipped.
[ERROR] Data category 'subjectField' not allowed at the Term level in line 6, skipped.
[ERROR] Data category 'definition' not allowed at the Term level in line 7, skipped.
[MSG] File includes IDs:
	C003
	C003en1

--- tbx fix_version
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version [version]</p>
			</sourceDesc>
			<sourceDesc>
				<p>a book about animals</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">animal book</descrip>
				</descripGrp>
				<langSet xml:lang="en">
					<tig id="C003en1">
						<term>chicken</term>
						<termNote type="partOfSpeech">noun</termNote>
					</tig>
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>

=== LangSet level disallowed data category

--- input convert
=MRCtermTable
A	workingLanguage	en
A	sourceDesc	a book about animals
C003en	xGraphic	my pet chicken	Link: wanda.jpg
C003en	subjectField	Restaurant Menus
C003en	context	the chicken pecked my eye
C003en	geographicalUsage	North America
C003en	grammaticalGender	feminine
C003en	partOfSpeech	noun
C003en	termLocation	menuItem
C003en	termType	fullForm
C003en	term	chicken
C003en	administrativeStatus	admittedTerm-admn-sts

--- log fix_version
[MSG] MRC2TBX converter version [version]
[ERROR] Data category 'xGraphic' not allowed at the LangSet level in line 4, skipped.
[ERROR] Data category 'subjectField' not allowed at the LangSet level in line 5, skipped.
[ERROR] Data category 'context' not allowed at the LangSet level in line 6, skipped.
[ERROR] Data category 'geographicalUsage' not allowed at the LangSet level in line 7, skipped.
[ERROR] Data category 'grammaticalGender' not allowed at the LangSet level in line 8, skipped.
[ERROR] Data category 'partOfSpeech' not allowed at the LangSet level in line 9, skipped.
[ERROR] Data category 'termLocation' not allowed at the LangSet level in line 10, skipped.
[ERROR] Data category 'termType' not allowed at the LangSet level in line 11, skipped.
[ERROR] Data category 'term' not allowed at the LangSet level in line 12, skipped.
[ERROR] Data category 'administrativeStatus' not allowed at the LangSet level in line 13, skipped.
[MSG] File includes IDs:
	C003

--- tbx fix_version
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version [version]</p>
			</sourceDesc>
			<sourceDesc>
				<p>a book about animals</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<langSet xml:lang="en">
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>

=== Concept level disallowed data category

--- input convert
=MRCtermTable
A	workingLanguage	en
A	sourceDesc	a book about animals
C003	subjectField	animals
C003	administrativeStatus	admittedTerm-admn-sts
C003	context	the chicken pecked my eye
C003	definition	a squaky bird
C003	geographicalUsage	North America
C003	grammaticalGender	feminine
C003	partOfSpeech	noun
C003	termLocation	menuItem
C003	termType	fullForm
C003	term	chicken

--- log fix_version
[MSG] MRC2TBX converter version [version]
[ERROR] Data category 'administrativeStatus' not allowed at the Concept level in line 5, skipped.
[ERROR] Data category 'context' not allowed at the Concept level in line 6, skipped.
[ERROR] Data category 'definition' not allowed at the Concept level in line 7, skipped.
[ERROR] Data category 'geographicalUsage' not allowed at the Concept level in line 8, skipped.
[ERROR] Data category 'grammaticalGender' not allowed at the Concept level in line 9, skipped.
[ERROR] Data category 'partOfSpeech' not allowed at the Concept level in line 10, skipped.
[ERROR] Data category 'termLocation' not allowed at the Concept level in line 11, skipped.
[ERROR] Data category 'termType' not allowed at the Concept level in line 12, skipped.
[ERROR] Data category 'term' not allowed at the Concept level in line 13, skipped.
[MSG] File includes IDs:
	C003

--- tbx fix_version
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version [version]</p>
			</sourceDesc>
			<sourceDesc>
				<p>a book about animals</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">animals</descrip>
				</descripGrp>
			</termEntry>
		</body>
	</text>
</martif>

=== invalid header category

--- input convert
=MRCtermTable
A	workingLanguage	en
A	sourceDesc	a restaurant menu in English and French
A	definition	some random definition
C003	subjectField	Restaurant Menus
C003fr1	term	poulet
C003fr1	partOfSpeech	noun

--- log fix_version
[MSG] MRC2TBX converter version [version]
[ERROR] Could not interpret header line 4, skipped.
[MSG] File includes IDs:
	C003
	C003fr1
	
--- tbx fix_version
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version [version]</p>
			</sourceDesc>
			<sourceDesc>
				<p>a restaurant menu in English and French</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">Restaurant Menus</descrip>
				</descripGrp>
				<langSet xml:lang="fr">
					<tig id="C003fr1">
						<term>poulet</term>
						<termNote type="partOfSpeech">noun</termNote>
					</tig>
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>

=== missing sourceDesc in header

--- input convert
=MRCtermTable
A	workingLanguage	en
C003	subjectField	Restaurant Menus
C003fr1	term	poulet
C003fr1	partOfSpeech	noun

--- log fix_version
[MSG] MRC2TBX converter version [version]
[ERROR] TBX header could not be completed because a required A-row is missing or malformed.

--- tbx fix_version eval
undef

=== missing workingLanguage in header

--- input convert
=MRCtermTable
A	sourceDesc	a restaurant menu in English and French
C003	subjectField	Restaurant Menus
C003fr1	term	poulet
C003fr1	partOfSpeech	noun

--- log fix_version
[MSG] MRC2TBX converter version [version]
[ERROR] TBX header could not be completed because a required A-row is missing or malformed.

--- tbx fix_version eval
undef

=== bad header
--- input convert
=MRCtermTable
A	workingLanguage	en
A	partOfSpeech	noun
A	sourceDesc	a restaurant menu in English and French
C003	subjectField	Restaurant Menus
C003fr1	term	poulet
C003fr1	partOfSpeech	noun

--- log fix_version
[MSG] MRC2TBX converter version [version]
[ERROR] Could not interpret header line 3, skipped.
[MSG] File includes IDs:
	C003
	C003fr1

--- tbx fix_version
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version [version]</p>
			</sourceDesc>
			<sourceDesc>
				<p>a restaurant menu in English and French</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">Restaurant Menus</descrip>
				</descripGrp>
				<langSet xml:lang="fr">
					<tig id="C003fr1">
						<term>poulet</term>
						<termNote type="partOfSpeech">noun</termNote>
					</tig>
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>

=== duplicate workingLanguage entry

--- input convert
=MRCtermTable
A	workingLanguage	en
A	workingLanguage	fr
A	sourceDesc	a restaurant menu in English and French
C003	subjectField	Restaurant Menus
C003fr1	term	poulet
C003fr1	partOfSpeech	noun

--- log fix_version
[MSG] MRC2TBX converter version [version]
[ERROR] Duplicate workingLanguage ignored in line 3.
[ERROR] Could not interpret header line 3, skipped.
[MSG] File includes IDs:
	C003
	C003fr1
	
--- tbx fix_version
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version [version]</p>
			</sourceDesc>
			<sourceDesc>
				<p>a restaurant menu in English and French</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">Restaurant Menus</descrip>
				</descripGrp>
				<langSet xml:lang="fr">
					<tig id="C003fr1">
						<term>poulet</term>
						<termNote type="partOfSpeech">noun</termNote>
					</tig>
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>

=== invalid value

--- input convert
=MRCtermTable
A	workingLanguage	en
A	sourceDesc	a restaurant menu in English and French
C003	subjectField	Restaurant Menus
C003fr1	term	poulet
C003fr1	partOfSpeech	junk

--- log fix_version
[MSG] MRC2TBX converter version [version]
[ERROR] 'junk' not a valid partOfSpeech in line 6, skipped. See picklist for valid values.
[ERROR] Term C003fr1 lacks a partOfSpeech row. This TBX file may not be machine processed. See line 5.
[ERROR] Term C003fr1 (see line 5) is lacking an element necessary for TBX-Basic.
	To make it valid for human use only, add one of:
		a definition (at the language level)
		an example of use in context (at the term level).
	To make it valid for human or machine processing, add its part of speech (at the term level).
[MSG] File includes IDs:
	C003
	C003fr1
	
--- tbx fix_version
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version [version]</p>
			</sourceDesc>
			<sourceDesc>
				<p>a restaurant menu in English and French</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">Restaurant Menus</descrip>
				</descripGrp>
				<langSet xml:lang="fr">
					<tig id="C003fr1">
						<term>poulet</term>
					</tig>
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>

=== missing partOfSpeech

--- input convert
=MRCtermTable
A	workingLanguage	en
A	sourceDesc	a restaurant menu in English and French
C003	subjectField	Restaurant Menus
C003fr1	term	poulet

--- log fix_version
[MSG] MRC2TBX converter version [version]
[ERROR] Term C003fr1 lacks a partOfSpeech row. This TBX file may not be machine processed. See line 4.
[ERROR] Term C003fr1 (see line 4) is lacking an element necessary for TBX-Basic.
	To make it valid for human use only, add one of:
		a definition (at the language level)
		an example of use in context (at the term level).
	To make it valid for human or machine processing, add its part of speech (at the term level).
[MSG] File includes IDs:
	C003
	C003fr1
	
--- tbx fix_version
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version [version]</p>
			</sourceDesc>
			<sourceDesc>
				<p>a restaurant menu in English and French</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">Restaurant Menus</descrip>
				</descripGrp>
				<langSet xml:lang="fr">
					<tig id="C003fr1">
						<term>poulet</term>
					</tig>
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>

=== bad category

--- input convert

=MRCtermTable
A	workingLanguage	en
A	sourceDesc	a restaurant menu in English and French
C003	subjectField	Restaurant Menus
C003fr1	term	poulet
C003fr1	POS	noun
C003fr1	partOfSpeech	noun

--- log fix_version
[MSG] MRC2TBX converter version [version]
[ERROR] Unknown data category 'POS' in line 6, skipped.
[MSG] File includes IDs:
	C003
	C003fr1

--- tbx fix_version
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version [version]</p>
			</sourceDesc>
			<sourceDesc>
				<p>a restaurant menu in English and French</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">Restaurant Menus</descrip>
				</descripGrp>
				<langSet xml:lang="fr">
					<tig id="C003fr1">
						<term>poulet</term>
						<termNote type="partOfSpeech">noun</termNote>
					</tig>
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>
