#test that the original example MRC converts correctly

use t::TestMRCConverter;
use Test::More;
plan tests => 2 * blocks();
use Test::XML;
use Test::LongString;

#loop through all blocks, convert the input, and compare with the output
for my $block ( blocks('input') ){
	my ($tbx, $log) = @{ $block->input };
	
	#compare tbx; check for undefs first
	if(defined $tbx and defined $block->tbx){
		is_xml($tbx, $block->tbx, "'" . $block->name . "' correct TBX output");
	}
	else{
		is($tbx,$block->tbx, "'" . $block->name . "' correct TBX output");
	}
	
	#check log for correct message
	is_string($log, $block->log,  "'" . $block->name . "' correct error(s) logged")
		or print $log;
}

__DATA__

=== invalid header category

--- input convert
=MRCtermTable
A	workingLanguage	en
A	sourceDesc	a restaurant menu in English and French
A	definition	some random definition
C003	subjectField	Restaurant Menus
C003fr1	term	poulet
C003fr1	partOfSpeech	noun

--- log fix_log
[MSG] MRC2TBX converter version 3.4
[ERROR] Could not interpret header line 4, skipped.
[MSG] File includes IDs:
	C003
	C003fr1
	
--- tbx
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version 3.4</p>
			</sourceDesc>
			<sourceDesc>
				<p>a restaurant menu in English and French</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">Restaurant Menus</descrip>
				</descripGrp>
				<langSet xml:lang="fr">
					<tig id="C003fr1">
						<term>poulet</term>
						<termNote type="partOfSpeech">noun</termNote>
					</tig>
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>

=== missing sourceDesc in header

--- input convert
=MRCtermTable
A	workingLanguage	en
C003	subjectField	Restaurant Menus
C003fr1	term	poulet
C003fr1	partOfSpeech	noun

--- log fix_log
[MSG] MRC2TBX converter version 3.4
[ERROR] TBX header could not be completed because a required A-row is missing or malformed.

--- tbx eval
undef

=== missing workingLanguage in header

--- input convert
=MRCtermTable
A	sourceDesc	a restaurant menu in English and French
C003	subjectField	Restaurant Menus
C003fr1	term	poulet
C003fr1	partOfSpeech	noun

--- log fix_log
[MSG] MRC2TBX converter version 3.4
[ERROR] TBX header could not be completed because a required A-row is missing or malformed.

--- tbx eval
undef

=== bad header
--- input convert
=MRCtermTable
A	workingLanguage	en
A	partOfSpeech	noun
A	sourceDesc	a restaurant menu in English and French
C003	subjectField	Restaurant Menus
C003fr1	term	poulet
C003fr1	partOfSpeech	noun

--- log fix_log
[MSG] MRC2TBX converter version [version]
[ERROR] Could not interpret header line 3, skipped.
[MSG] File includes IDs:
	C003
	C003fr1

--- tbx
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version 3.4</p>
			</sourceDesc>
			<sourceDesc>
				<p>a restaurant menu in English and French</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">Restaurant Menus</descrip>
				</descripGrp>
				<langSet xml:lang="fr">
					<tig id="C003fr1">
						<term>poulet</term>
						<termNote type="partOfSpeech">noun</termNote>
					</tig>
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>

=== duplicate workingLanguage entry

--- input convert
=MRCtermTable
A	workingLanguage	en
A	workingLanguage	fr
A	sourceDesc	a restaurant menu in English and French
C003	subjectField	Restaurant Menus
C003fr1	term	poulet
C003fr1	partOfSpeech	noun

--- log fix_log
[MSG] MRC2TBX converter version [version]
[ERROR] Duplicate workingLanguage ignored in line 3.
[ERROR] Could not interpret header line 3, skipped.
[MSG] File includes IDs:
	C003
	C003fr1
	
--- tbx
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version 3.4</p>
			</sourceDesc>
			<sourceDesc>
				<p>a restaurant menu in English and French</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">Restaurant Menus</descrip>
				</descripGrp>
				<langSet xml:lang="fr">
					<tig id="C003fr1">
						<term>poulet</term>
						<termNote type="partOfSpeech">noun</termNote>
					</tig>
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>

=== invalid value

--- input convert
=MRCtermTable
A	workingLanguage	en
A	sourceDesc	a restaurant menu in English and French
C003	subjectField	Restaurant Menus
C003fr1	term	poulet
C003fr1	partOfSpeech	junk

--- log fix_log
[MSG] MRC2TBX converter version [version]
[ERROR] 'junk' not a valid partOfSpeech in line 6, skipped. See picklist for valid values.
[ERROR] lacks a partOfSpeech row. This TBX file may not be machine processed. See line 5.
[ERROR] Term C003fr1 (see line 5) is lacking an element necessary for TBX-Basic.
	To make it valid for human use only, add one of:
		a definition (at the language level)
		an example of use in context (at the term level).
	To make it valid for human or machine processing, add its part of speech (at the term level).
[MSG] File includes IDs:
	C003
	C003fr1
	
--- tbx
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version 3.4</p>
			</sourceDesc>
			<sourceDesc>
				<p>a restaurant menu in English and French</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">Restaurant Menus</descrip>
				</descripGrp>
				<langSet xml:lang="fr">
					<tig id="C003fr1">
						<term>poulet</term>
					</tig>
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>

=== missing partOfSpeech

--- input convert
=MRCtermTable
A	workingLanguage	en
A	sourceDesc	a restaurant menu in English and French
C003	subjectField	Restaurant Menus
C003fr1	term	poulet

--- log fix_log
[MSG] MRC2TBX converter version [version]
[ERROR] lacks a partOfSpeech row. This TBX file may not be machine processed. See line 4.
[ERROR] Term C003fr1 (see line 4) is lacking an element necessary for TBX-Basic.
	To make it valid for human use only, add one of:
		a definition (at the language level)
		an example of use in context (at the term level).
	To make it valid for human or machine processing, add its part of speech (at the term level).
[MSG] File includes IDs:
	C003
	C003fr1
	
--- tbx
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version 3.4</p>
			</sourceDesc>
			<sourceDesc>
				<p>a restaurant menu in English and French</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">Restaurant Menus</descrip>
				</descripGrp>
				<langSet xml:lang="fr">
					<tig id="C003fr1">
						<term>poulet</term>
					</tig>
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>

=== bad category

--- input convert

=MRCtermTable
A	workingLanguage	en
A	sourceDesc	a restaurant menu in English and French
C003	subjectField	Restaurant Menus
C003fr1	term	poulet
C003fr1	POS	noun
C003fr1	partOfSpeech	noun

--- log fix_log
[MSG] MRC2TBX converter version [version]
[ERROR] Unknown data category 'POS' in line 6, skipped.
[MSG] File includes IDs:
	C003
	C003fr1

--- tbx
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE martif SYSTEM "TBXBasiccoreStructV02.dtd">
<martif type="TBX-Basic-V1" xml:lang="en">
	<martifHeader>
		<fileDesc>
			<titleStmt>
				<title>termbase from MRC file</title>
			</titleStmt>
			<sourceDesc>
				<p>generated by TBX::convert::MRC version 3.4</p>
			</sourceDesc>
			<sourceDesc>
				<p>a restaurant menu in English and French</p>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<p type="DCSName">TBXBasicXCSV02.xcs</p>
		</encodingDesc>
	</martifHeader>
	<text>
		<body>
			<termEntry id="C003">
				<descripGrp>
					<descrip type="subjectField">Restaurant Menus</descrip>
				</descripGrp>
				<langSet xml:lang="fr">
					<tig id="C003fr1">
						<term>poulet</term>
						<termNote type="partOfSpeech">noun</termNote>
					</tig>
				</langSet>
			</termEntry>
		</body>
	</text>
</martif>
